name: Curseforge Release

on:
  workflow_call:
    secrets:
      envPAT:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: curseforge-upload-params

      - name: Debug Artifact Content
        run: |
          # Debug the content of the artifact file
          echo "Artifact Content:"
          cat curseforge-upload-params.txt
          
      - shell: bash
        run: |
          # Read the content of the artifact file
          ARTIFACT_CONTENT=$(cat curseforge-upload-params.txt)
          
          # Split the content into an array based on the pipe character
          IFS='|' read -ra VARIABLES <<< "$ARTIFACT_CONTENT"

          # Debug the content of the array
          echo "Array Content:"
          for index in "${!VARIABLES[@]}"; do
            echo "[$index] ${VARIABLES[index]}"
          done

          ZIP_FILE_NAME="${VARIABLES[0]}"
          DISPLAY_NAME="${VARIABLES[1]}"
          CURSEFORGE_PROJECT_ID="${VARIABLES[2]}"
          CHANGELOG="See changelog.txt"


      - name: Print Parameters
        run: |
          echo "ZIP_FILE_NAME: $ZIP_FILE_NAME"
          echo "DISPLAY_NAME: $DISPLAY_NAME"
          echo "CHANGELOG: $CHANGELOG"
          echo "CURSEFORGE_PROJECT_ID: $CURSEFORGE_PROJECT_ID"
