name: Curseforge Release

on:
  workflow_call:
    inputs:
      zip-file-path:
        required: true
        type: string
      addon-display-name:
        required: true
        type: string
      change-log:
        required: true
        type: string
      curse-project-id:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print Parameters
        run: |
          echo "ZIP_FILE_NAME: ${{ inputs.zip-file-path }}"
          echo "DISPLAY_NAME: ${{ inputs.addon-display-name }}"
          echo "CHANGELOG: ${{ inputs.change-log }}"
          echo "CURSEFORGE_PROJECT_ID: ${{ inputs.curse-project-id }}"
