name: Curseforge Release

on:
  workflow_call:
    secrets:
      envPAT:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send-to-curse:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_PROD_API_TOKEN }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download artifact  (Zip File)
        uses: actions/download-artifact@v3
        with:
          name: curseforge-upload-zip
      
      - name: Download artifact  (Curse Params)
        uses: actions/download-artifact@v3
        with:
          name: curseforge-upload-params

      - name: Debug Artifact Content
        run: |
          # Debug the content of the artifact file
          echo "Artifact Content:"
          cat curseforge-upload-params.txt
          
      - shell: bash
        run: |
          # Read the content of the artifact file
          ARTIFACT_CONTENT=$(cat curseforge-upload-params.txt)
          
          # Split the content into an array based on the pipe character
          IFS='|' read -ra VARIABLES <<< "$ARTIFACT_CONTENT"

          # Debug the content of the array
          echo "Array Content:"
          for index in "${!VARIABLES[@]}"; do
            echo "[$index] ${VARIABLES[index]}"
          done
          
          echo "ZIP_FILE_NAME=${VARIABLES[0]}" >> $GITHUB_ENV
          echo "DISPLAY_NAME=${VARIABLES[1]}" >> $GITHUB_ENV
          echo "CURSEFORGE_PROJECT_ID=${VARIABLES[2]}" >> $GITHUB_ENV
          echo "CHANGELOG=\"See changelog.txt\"" >> $GITHUB_ENV

      - name: Print Parameters
        run: |
          echo "ZIP_FILE_NAME: $ZIP_FILE_NAME"
          echo "DISPLAY_NAME: $DISPLAY_NAME"
          echo "CHANGELOG: $CHANGELOG"
          echo "CURSEFORGE_PROJECT_ID: $CURSEFORGE_PROJECT_ID"

      - name: Upload to Curseforge API
        run: |
          API_URL="https://wow.curseforge.com/api/projects/${{ env.CURSEFORGE_PROJECT_ID }}/upload-file"
          
          curl -L -X POST \
          -H "x-api-token: ${{ secrets.CURSEFORGE_PROD_API_TOKEN }}" \
          -F "metadata={\"displayName\": \"$DISPLAY_NAME\", \"gameVersions\": [10215], \"releaseType\": \"release\", \"changelog\": \"$CHANGELOG\"}"  \
          -F "file=@$ZIP_FILE_NAME" \
          "$API_URL"
